name: Bug report
description: Create a report to help us improve
labels: ["bug"]
assignees: [""]
body:
  - type: markdown
    attributes:
      value: |
        Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

        [![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)
