# a lot of this came from brew bundle dump
cask_args appdir: "~/Applications"
tap "caskroom/cask"
tap "telemachus/brew", "https://telemachus@bitbucket.org/telemachus/brew.git"

## cask apps ##
# xquartz dependency
cask "xquartz"

# chat
cask "slack"
# fb messenger
#cask "goofy"
# secure chat
cask "keybase"
# browsers
cask "google-chrome"
cask "firefox"
# terminal
cask "iterm2"
# editors
#cask "atom"
#cask "intellij-idea-ce"
cask "pycharm"
cask "visual-studio-code"
# source control gui
cask "sourcetree"
# database
cask "sqlworkbenchj"
cask "mysqlworkbench"
# data visualization
cask "tableau-reader"
# vms
cask "virtualbox"
cask "virtualbox-extension-pack"
# vm manager
cask "vagrant"
cask "vagrant-manager"
# containers
cask "docker"
# aws creds manager
cask "aws-vault"
# cloud drives
cask "google-drive-file-stream"
cask "onedrive"
# install java dependency
cask "java"
# authenticator
cask "authy"
# window manager
cask "spectacle"
# remove ambient blue at night
cask "flux"
# disable monitor
cask "disablemonitor"
# install different calendar
cask "itsycal"
# install js desktop widgets
cask "ubersicht"
# disk usage analyzer
cask "GrandPerspective"
# clean up
cask "cleanup"
cask "clean-me"
# remove apps completely
cask "appcleaner"
# cast to screen
cask "mkchromecast"
# player
cask "vlc"
# uploader
cask "transmit"
# install image editor
cask "gimp"
# install weather menu applet
#cask "temps"
# clipboard manager
cask "clipy"
# show keyboard shortcuts for apps
cask "cheatsheet"
# keep monitor from sleeping
cask "keepingyouawake"
# vpn software to connect to multiple
cask "tunnelblick"
# monospace font
tap "homebrew/cask-fonts"
cask "font-fira-code"

## brew cli tools ##

# hit rest endpoints
brew "curl"
brew "httpie"
brew "wget"

# editors
brew "vim"
brew "neovim"
brew "nano"

# better greps
brew "ack"
brew "ripgrep"
brew "the_silver_searcher"

# rust version of cat
brew "bat"

# convert data like yaml2json
brew "remarshal"

# set default applications for file extensions
brew "duti"

# rdesktop for rdp
brew "rdesktop"

# make oneliner sql readable
brew "sqlparse"

# youtube downloader
brew "youtube-dl"
brew "ffmpeg"

# docker
brew "docker"
brew "docker-compose"
brew "docker-machine"
brew "xhyve"
brew "docker-machine-driver-xhyve"

## search data
# json
brew "jq"
# yaml
brew "yq"
# sql against csv
brew "q"
# better grep
brew "sift"

# install dependencies of pyenv
brew "readline"
brew "xz"
brew "pyenv"

# git
brew "git"
brew "git-extras"

# tldr docs better than man
brew "tldr"

# language specific compilation and env tooling
brew "nvm"
brew "jenv"

# aws
brew "awscli"

# from brew dump and uncategorized
brew "adns"
brew "ansible"
brew "asciidoc"
brew "cmake"
brew "coreutils"
brew "docbook"
brew "dos2unix"
brew "findutils"
brew "freetype"
brew "gawk"
brew "gdbm"
brew "geos"
brew "gettext"
brew "gmp"
brew "gnu-getopt"
brew "gnu-indent"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-time"
brew "gnupg"
brew "gnutls"
brew "go"
# dependency for goofys
brew "osxfuse"
# this will mount s3 buckets locally
brew "goofys"
brew "grep"
brew "htop"
brew "icu4c"
# modify images
brew "imagemagick"
brew "jpeg"
brew "json-c"
brew "lftp"
brew "libassuan"
brew "libdnet"
brew "libevent"
brew "libffi"
brew "libgcrypt"
brew "libgit2"
brew "libgpg-error"
brew "libidn"
brew "libksba"
brew "libpng"
brew "libssh2"
brew "libtasn1"
brew "libtiff"
brew "libtool"
brew "libunistring"
brew "libusb"
brew "libyaml"
# configuration saver
brew "mackup"
brew "make"
brew "mas"
brew "moreutils"
brew "mpack"
brew "mpfr"
brew "ncdu"
brew "nettle"
brew "nmap"
brew "npth"
brew "oniguruma"
brew "openssl"
brew "p11-kit"
brew "p7zip"
brew "pass"
brew "pcre"
brew "pinentry"
brew "pkg-config"
brew "postgresql"
brew "proj"
brew "pyqt"
brew "python"
brew "python3"
brew "qrencode"
brew "qt"
brew "rsync"
brew "saltstack"
brew "sip"
brew "sqlite"
brew "ssh-copy-id"
brew "terraform"
brew "tmux"
brew "todo-txt"
brew "trash"
brew "tree"
brew "watch"
brew "wrk"
brew "xmlstarlet"
brew "zeromq"
brew "zmap"
brew "zsh"
