# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # 18.04 LTS which is EOL by April 2023
  config.vm.box = "ubuntu/bionic64"
  # 20.04 LTS which is EOL by April 2025
  #config.vm.box = "ubuntu/focal64"
  
  # reboot after install guest additions
  # if Vagrant.has_plugin?("vagrant-vbguest")
  #   auto_reboot = true
  # end

  # setup a cache so subsequent reloads will not redownload everything
  if Vagrant.has_plugin?("vagrant-cachier")
    # Configure cached packages to be shared between instances of the same base box.
    # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
    config.cache.scope = :box

    # OPTIONAL: If you are using VirtualBox, you might want to use that to enable
    # NFS for shared folders. This is also very useful for vagrant-libvirt if you
    # want bi-directional sync
    # config.cache.synced_folder_opts = {
      # type: :nfs,
      # The nolock option can be useful for an NFSv3 client that wants to avoid the
      # NLM sideband protocol. Without this option, apt-get might hang if it tries
      # to lock files needed for /var/cache/* operations. All of this can be avoided
      # by using NFSv4 everywhere. Please note that the tcp option is not the default.
      # mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
    # }
    # For more information please check http://docs.vagrantup.com/v2/synced-folders/basic_usage.html
  end

  config.disksize.size = '30GB'

  config.vm.network "forwarded_port", guest: 4000, host: 4000,
                    auto_correct: true

  config.vm.synced_folder "C:\\", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.gui    = true
    vb.memory = "4096"
    vb.cpus   = "1"
    vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional'] 
  end

  config.vm.provision "shell", path: "vagrant-bootstrap.sh"
end
